import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import ICodeThis from './components/util';
import IcT from "./components/icons";


const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
        <style>
@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@500&family=Roboto:wght@100&display=swap');
</style>
      </Head>
      <main>
        <ICodeThis />
      </main>
    </>
  );
};

export default Home;
