import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import ICodeThis from './components/util';


const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main class="bg-gradient-to-l from-slate-100 to-slate-600 flex items-center justify-center min-h-screen">
        <ICodeThis />
      </main>
    </>
  );
};

export default Home;
